export const DEFAULT_MAS_WORKFLOW_INPUT: Record<string, unknown> = {
  stay_id: '18530850',
  subject_id: '37186254',
  hadm_id: '25480845.0',
  intime: '2167-2-12 23:52',
  outtime: '2167-2-13 17:15',
  gender: 'M',
  race: 'WHITE',
  arrival_transport: 'AMBULANCE',
  disposition: 'HOME',
  temperature: '96.6',
  heartrate: '85.0',
  resprate: '16.0',
  o2sat: '97.0',
  sbp: '184.0',
  dbp: '',
  pain: '10',
  acuity: '2',
  chiefcomplaint: 'Epigastric pain',
  invasive_ventilation: '0',
  invasive_ventilation_beyond_1h: '0',
  non_invasive_ventilation: '0',
  transfer2surgeryin1h: '0',
  transfer_to_surgery_beyond_1h: '0',
  transfer_to_icu_in_1h: '0',
  transfer_to_icu_beyond_1h: '0',
  transfer_within_1h: '0',
  transfer_beyond_1h: '0',
  expired_within_1h: '0',
  expired_beyond_1h: '0',
  tier1_med_usage_1h: '0',
  tier1_med_usage_beyond_1h: '0',
  tier2_med_usage: '0',
  tier3_med_usage: '0',
  tier4_med_usage: '0',
  psychotropic_med_within_120min: '0',
  transfusion_within_1h: '0',
  transfusion_beyond_1h: '0',
  red_cell_order_more_than_1: '0',
  intraosseous_line_placed: '0',
  critical_procedure: '0',
  lab_event_count: '58',
  microbio_event_count: '0',
  exam_count: '2',
  intravenous_fluids: '0',
  intravenous: '2',
  intramuscular: '0',
  nebulized_medications: '0',
  oral_medications: '4',
  consults_count: '0',
  procedure_count: '0',
  age: '62.11705238',
  resources_used: '4',
  tiragecase:
    'A 61-year-old male presented to the emergency department via ambulance with a chief complaint of severe right upper quadrant abdominal pain, rated 10/10, accompanied by nausea, vomiting, constipation, and reduced oral intake. He has a significant medical history, including coronary artery disease, hypertension, hyperlipidemia, left ventricular hypertrophy, cholelithiasis, diverticulosis, colon adenoma, and a previous lacunar infarction. Earlier in the day, he was discharged with a diagnosis of gallstones and advised to follow up for surgery but returned with exacerbated symptoms. On arrival, his vital signs showed hypertension (BP 184/0) and hypothermia (T 96.6掳F).',
  expert_1_opinion: 'AGREE',
  expert_2_opinion: 'AGREE',
  expert_3_opinion: '',
  final_decision: 'RETAIN',
};
