from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.agentic.workflows.registry import get_workflow_spec
from app.models.mas_test_case import MasTestCase


WORKFLOW_ID = "esi_swarm_v1"


SEEDED_ESI_SWARM_V1_CASES = [
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "8",
            "chiefcomplaint": "s/p Fall, Head injury",
            "age": 79.03214573,
            "tiragecase": "79-year-old white male with depression, acute congestive heart failure, prior mitral valve repair with CABG, prostate cancer post-TURP, OSA, hypertension, and Alzheimer's disease presented after an unwitnessed fall with head injury, acute confusion, nausea, and vomiting.",
            "temperature": None,
            "heartrate": 68.0,
            "resprate": 16.0,
            "o2sat": 98.0,
            "sbp": 166.0,
            "dbp": 72.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "6",
            "chiefcomplaint": "Head lac, s/p Fall",
            "age": 52.21801877,
            "tiragecase": "Middle-aged male with epilepsy presented after seizure-related fall and forehead laceration, with multiple typical seizures observed during evaluation and postictal confusion.",
            "temperature": 97.3,
            "heartrate": 70.0,
            "resprate": 18.0,
            "o2sat": 95.0,
            "sbp": 145.0,
            "dbp": 80.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "10",
            "chiefcomplaint": "Epigastric pain",
            "age": 62.11705238,
            "tiragecase": "Older male returned after same-day discharge for gallstones with severe RUQ abdominal pain, nausea, vomiting, constipation, reduced intake, and markedly elevated blood pressure.",
            "temperature": 96.6,
            "heartrate": 85.0,
            "resprate": 16.0,
            "o2sat": 97.0,
            "sbp": 184.0,
            "dbp": None,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "Critical",
            "chiefcomplaint": "Transfer, Respiratory distress",
            "age": 53.46908207,
            "tiragecase": "Male with COPD, CHF, dialysis dependence, aortic thrombosis, CKD, and hepatitis C presented with respiratory distress and dyspnea requiring close monitoring and supportive care.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "uta",
            "chiefcomplaint": "Chest pain",
            "age": 63.81083037,
            "tiragecase": "Male with mechanical aortic valve, aneurysm repair, diabetes, and ventricular tachycardia history presented with palpitations, dizziness, absent vitals on arrival, and concern for cardiac emergency requiring ACLS.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "8",
            "chiefcomplaint": "Chest pain, Dyspnea",
            "age": 53.42544091,
            "tiragecase": "Male with cirrhosis, COPD, diabetes, and jugular vein thrombosis presented from liver clinic with productive cough, sharp chest pain with coughing, fatigue, mild DOE, and wheezing.",
            "temperature": 98.9,
            "heartrate": 91.0,
            "resprate": 22.0,
            "o2sat": 97.0,
            "sbp": 119.0,
            "dbp": 71.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "0",
            "chiefcomplaint": "L Weakness",
            "age": 78.62967392,
            "tiragecase": "Older male presented with progressive left-sided weakness, numbness, and clumsiness concerning for acute neurologic deficit after a recent fall.",
            "temperature": 98.7,
            "heartrate": 80.0,
            "resprate": 16.0,
            "o2sat": 99.0,
            "sbp": 115.0,
            "dbp": 67.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": None,
            "chiefcomplaint": "Unresponsive, Respiratory distress",
            "age": 91.03527152,
            "tiragecase": "Elderly male with recent massive stroke arrived unresponsive and obtunded with shallow respirations after hypotension and respiratory distress.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "10",
            "chiefcomplaint": "Difficulty swallowing, Transfer",
            "age": 64.35184435,
            "tiragecase": "Male post C-spine surgery presented with dysphagia, neck swelling, hoarseness, inability to swallow, hypertensive urgency, headache, and chest pain.",
            "temperature": 97.9,
            "heartrate": 87.0,
            "resprate": 18.0,
            "o2sat": 94.0,
            "sbp": 180.0,
            "dbp": 104.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "UNKNOWN",
            "pain": "13",
            "chiefcomplaint": "#NAME?",
            "age": 55.43337918,
            "tiragecase": "Male with ESRD, CAD, CHF, diabetes, and recent wet gangrene/osteomyelitis presented with fever, sepsis concern, hypotension history, agitation, and anxiety.",
            "temperature": 95.6,
            "heartrate": 79.0,
            "resprate": 20.0,
            "o2sat": 96.0,
            "sbp": 136.0,
            "dbp": 84.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "BLACK/AFRICAN AMERICAN",
            "arrival_transport": "WALK IN",
            "pain": "5",
            "chiefcomplaint": "Chest pain",
            "age": 54.53502122,
            "tiragecase": "Male with AF, cervical cord compression, and substance use history presented with substernal chest pain radiating to arm and jaw, diaphoresis, SOB, palpitations, and orthopnea.",
            "temperature": 97.5,
            "heartrate": 86.0,
            "resprate": 18.0,
            "o2sat": 99.0,
            "sbp": 139.0,
            "dbp": 84.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "Fever, Pneumonia, Transfer",
            "age": 78.39096415,
            "tiragecase": "Older female with metastatic malignancy and multiple chronic illnesses presented with presumed pneumonia, shock, severe hypotension, SVT, recent intubation, and central line placement.",
            "temperature": 98.8,
            "heartrate": 150.0,
            "resprate": 20.0,
            "o2sat": 97.0,
            "sbp": 120.0,
            "dbp": 58.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE - RUSSIAN",
            "arrival_transport": "AMBULANCE",
            "pain": "13",
            "chiefcomplaint": "Weakness, Hypotension",
            "age": 75.26375891,
            "tiragecase": "Male with CAD, heart failure, COPD, and presumed cholangiocarcinoma presented with weakness, fatigue, dehydration, emesis, and profound hypotension.",
            "temperature": None,
            "heartrate": 58.0,
            "resprate": None,
            "o2sat": 96.0,
            "sbp": 74.0,
            "dbp": 47.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "PATIENT DECLINED TO ANSWER",
            "arrival_transport": "UNKNOWN",
            "pain": "4",
            "chiefcomplaint": "BASIC TRAUMA",
            "age": 91.80183709,
            "tiragecase": "Very elderly female with Parkinson's disease presented after mechanical fall with right-sided chest pain and stable vitals.",
            "temperature": None,
            "heartrate": 96.0,
            "resprate": 19.0,
            "o2sat": 100.0,
            "sbp": 157.0,
            "dbp": 77.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE - RUSSIAN",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "Dyspnea, Pedal edema",
            "age": 82.96188547,
            "tiragecase": "Female with heart failure, aortic stenosis, strokes, COPD, and chronic urinary retention presented with SOB, chest pain, and bilateral pedal edema.",
            "temperature": 98.5,
            "heartrate": 95.0,
            "resprate": 18.0,
            "o2sat": 100.0,
            "sbp": 160.0,
            "dbp": 54.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "8",
            "chiefcomplaint": "RECTAL ABSCESS",
            "age": 45.78984177,
            "tiragecase": "Male with HIV, diabetes, hidradenitis, CKD, and obesity presented with painful perianal abscess without systemic symptoms.",
            "temperature": 97.8,
            "heartrate": 98.0,
            "resprate": 18.0,
            "o2sat": 100.0,
            "sbp": 126.0,
            "dbp": 71.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "1",
            "chiefcomplaint": "Chest pain",
            "age": 80.61459252,
            "tiragecase": "Elderly male with COPD, CAD, CKD, and recent femur fracture presented with pleuritic left chest pain and bilateral calf pain, but stable vitals.",
            "temperature": 98.0,
            "heartrate": 82.0,
            "resprate": 18.0,
            "o2sat": 95.0,
            "sbp": 116.0,
            "dbp": 62.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "M",
            "race": "UNKNOWN",
            "arrival_transport": "UNKNOWN",
            "pain": "unable",
            "chiefcomplaint": "Transfer, Intubated",
            "age": 72.83718276,
            "tiragecase": "Male with severe COPD and multiple comorbidities transferred intubated for hypoxemic and hypercarbic respiratory failure after recent discharge.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": None,
            "chiefcomplaint": "ALTERED LEVEL OF CONSCIOUSNESS",
            "age": 76.49987786,
            "tiragecase": "Female with gliomatosis cerebri and seizure disorder found unresponsive with airway compromise, right gaze deviation, and left hemiparesis.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE - RUSSIAN",
            "arrival_transport": "AMBULANCE",
            "pain": None,
            "chiefcomplaint": "DYSPNEA",
            "age": 83.07913802,
            "tiragecase": "Older female with CAD, diabetes, hypertension, and metastatic RCC presented in acute respiratory distress after recent CHF-related discharge.",
            "temperature": None,
            "heartrate": None,
            "resprate": 38.0,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "0",
            "chiefcomplaint": "Weakness",
            "age": 44.1489015,
            "tiragecase": "Male with psychiatric history and systemic eosinophilia presented with sudden inability to move extremities and wheelchair dependence.",
            "temperature": 98.7,
            "heartrate": 92.0,
            "resprate": 18.0,
            "o2sat": 100.0,
            "sbp": 145.0,
            "dbp": 97.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "7",
            "chiefcomplaint": "Lower abdominal pain",
            "age": 49.76851634,
            "tiragecase": "Middle-aged female with isolated lower abdominal pain and stable vitals.",
            "temperature": 98.3,
            "heartrate": 75.0,
            "resprate": 14.0,
            "o2sat": 100.0,
            "sbp": 138.0,
            "dbp": 90.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "ALTERED LEVEL OF CONSCIOUSNESS",
            "age": 66.63059994,
            "tiragecase": "Male with esophageal cancer, chronic pain on opioids, COPD, and prior stroke presented with AMS, pinpoint pupils, slurred speech, and possible narcotic overdose.",
            "temperature": 97.7,
            "heartrate": 120.0,
            "resprate": 18.0,
            "o2sat": 93.0,
            "sbp": 168.0,
            "dbp": 106.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "9",
            "chiefcomplaint": "Acute Pelvic pain",
            "age": 68.43308166,
            "tiragecase": "Older female arrived by ambulance with acute pelvic pain rated 9/10 and otherwise stable vitals.",
            "temperature": 98.4,
            "heartrate": 65.0,
            "resprate": 16.0,
            "o2sat": 94.0,
            "sbp": 143.0,
            "dbp": 72.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "10",
            "chiefcomplaint": "Dyspnea",
            "age": 64.2934765,
            "tiragecase": "Female with ovarian cancer, prior MI, DVT/PE, diabetes, HTN, and malignant pleural effusion presented with worsening dyspnea and clogged Pleurx catheter.",
            "temperature": 98.1,
            "heartrate": 90.0,
            "resprate": 18.0,
            "o2sat": 100.0,
            "sbp": 102.0,
            "dbp": 69.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "Slurred speech",
            "age": 97.2277849,
            "tiragecase": "Very elderly male with recurrent transient slurred speech and right facial droop presented after another TIA/stroke-like episode.",
            "temperature": 97.6,
            "heartrate": 68.0,
            "resprate": 18.0,
            "o2sat": 99.0,
            "sbp": 152.0,
            "dbp": 82.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": None,
            "chiefcomplaint": "SEPSIS",
            "age": 55.31660242,
            "tiragecase": "Male with infected sacral decubitus wounds, respiratory failure requiring mechanical ventilation, dialysis, and critical hypotension presented with sepsis.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "UNKNOWN",
            "arrival_transport": "UNKNOWN",
            "pain": None,
            "chiefcomplaint": "SZ",
            "age": 20.14207665,
            "tiragecase": "Young male college freshman with depression on Wellbutrin presented after tonic-clonic seizures following binge drinking and suspected cocaine use, with tachycardia and major weight loss.",
            "temperature": None,
            "heartrate": 146.0,
            "resprate": None,
            "o2sat": None,
            "sbp": 127.0,
            "dbp": 73.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "ASIAN - CHINESE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "N/V, Weakness",
            "age": 58.51407058,
            "tiragecase": "Male with ESRD, hypertension, and adrenal insufficiency presented with nausea, vomiting, left-sided weakness, possible gaze deviation, active emesis, and severe hypertension.",
            "temperature": 97.0,
            "heartrate": 108.0,
            "resprate": 22.0,
            "o2sat": 97.0,
            "sbp": 198.0,
            "dbp": 107.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "HISPANIC/LATINO - HONDURAN",
            "arrival_transport": "WALK IN",
            "pain": "3",
            "chiefcomplaint": "Finger laceration",
            "age": 26.09154129,
            "tiragecase": "Young male walk-in with isolated finger laceration, mild pain, and stable vitals.",
            "temperature": 99.0,
            "heartrate": 90.0,
            "resprate": 18.0,
            "o2sat": 100.0,
            "sbp": 147.0,
            "dbp": 87.0,
        },
        "expected": {"final_esi_level": 4},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "UNKNOWN",
            "pain": "Critical",
            "chiefcomplaint": "Found down",
            "age": 62.13048997,
            "tiragecase": "Male with pacemaker presented in out-of-hospital asystolic cardiac arrest after collapse while swimming, remaining pulseless on arrival.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "ASIAN - CHINESE",
            "arrival_transport": "WALK IN",
            "pain": "3",
            "chiefcomplaint": "Finger laceration",
            "age": 58.69628622,
            "tiragecase": "Female walk-in with isolated finger laceration, mild pain, and stable vitals.",
            "temperature": 97.6,
            "heartrate": 96.0,
            "resprate": 16.0,
            "o2sat": 100.0,
            "sbp": 179.0,
            "dbp": 72.0,
        },
        "expected": {"final_esi_level": 4},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "UA",
            "chiefcomplaint": "MVC, Transfer",
            "age": 52.47791373,
            "tiragecase": "Female transferred after MVC into a tree with chest pain and oxygen requirement after trauma, under surgical care with chest tube management.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE - OTHER EUROPEAN",
            "arrival_transport": "UNKNOWN",
            "pain": "crit",
            "chiefcomplaint": "Chest pain",
            "age": 74.89827429,
            "tiragecase": "Older female transfer for STEMI after vague unwellness and nausea over two days.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "BLACK/AFRICAN AMERICAN",
            "arrival_transport": "WALK IN",
            "pain": "8",
            "chiefcomplaint": "R Wrist pain",
            "age": 23.51929991,
            "tiragecase": "Young female walk-in with isolated right wrist pain, stable vitals, and no other concerning symptoms.",
            "temperature": 99.4,
            "heartrate": 72.0,
            "resprate": 20.0,
            "o2sat": 99.0,
            "sbp": 114.0,
            "dbp": 74.0,
        },
        "expected": {"final_esi_level": 4},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "7",
            "chiefcomplaint": "R Foot swelling",
            "age": 58.61738572,
            "tiragecase": "Male walk-in with right foot swelling and pain, hypertension history, and stable vitals.",
            "temperature": 97.9,
            "heartrate": 61.0,
            "resprate": 16.0,
            "o2sat": 100.0,
            "sbp": 153.0,
            "dbp": 100.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "Critical",
            "chiefcomplaint": "Cardiac arrest",
            "age": 75.36495019,
            "tiragecase": "Male transported by ambulance after witnessed cardiac arrest with prolonged downtime and no spontaneous vitals on arrival.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "Overdose",
            "age": 18.25583114,
            "tiragecase": "Young female with intentional large Wellbutrin overdose presented after generalized seizure and was intubated for airway protection.",
            "temperature": None,
            "heartrate": None,
            "resprate": None,
            "o2sat": None,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "10",
            "chiefcomplaint": "Abd pain, Abdominal distention",
            "age": 79.7448563,
            "tiragecase": "Older male with multiple comorbidities and anticoagulation presented with severe abdominal pain and abdominal distention but stable vitals.",
            "temperature": 97.2,
            "heartrate": 100.0,
            "resprate": 16.0,
            "o2sat": 99.0,
            "sbp": 122.0,
            "dbp": 84.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "BLACK/AFRICAN AMERICAN",
            "arrival_transport": "WALK IN",
            "pain": "7",
            "chiefcomplaint": "Abd pain, Vomiting, Nausea, Dyspnea",
            "age": 71.34845253,
            "tiragecase": "Male with metastatic RCC, prior PE, CKD, and recent nephrectomy presented with abdominal pain, vomiting, transient chest pain, dyspnea, and low oxygen saturation.",
            "temperature": 99.6,
            "heartrate": 85.0,
            "resprate": 16.0,
            "o2sat": 90.0,
            "sbp": 166.0,
            "dbp": 84.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "0",
            "chiefcomplaint": "Suture removal",
            "age": 39.83115206,
            "tiragecase": "Young female walk-in for uncomplicated suture removal with stable vitals and no pain.",
            "temperature": 98.1,
            "heartrate": 74.0,
            "resprate": 16.0,
            "o2sat": 100.0,
            "sbp": 125.0,
            "dbp": 69.0,
        },
        "expected": {"final_esi_level": 5},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "9",
            "chiefcomplaint": "BACK PAIN",
            "age": 50.84502961,
            "tiragecase": "Male with chronic spinal pain and stimulators presented with acute worsening lumbar pain after feeling a pop while walking, without other red flags.",
            "temperature": 97.2,
            "heartrate": 72.0,
            "resprate": None,
            "o2sat": 100.0,
            "sbp": 138.0,
            "dbp": 77.0,
        },
        "expected": {"final_esi_level": 4},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "13",
            "chiefcomplaint": "Abd pain, Transfer",
            "age": 67.70127591,
            "tiragecase": "Female with HTN and HLD presented with abdominal pain, altered mental status, and hemodynamic instability requiring immediate intervention.",
            "temperature": 98.1,
            "heartrate": 115.0,
            "resprate": 16.0,
            "o2sat": 100.0,
            "sbp": 125.0,
            "dbp": 95.0,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "SDH",
            "age": 69.40509861,
            "tiragecase": "Female with prior stroke and chronic dizziness presented with persistent headache and falls, increasing unsteadiness, and baseline neurologic deficits.",
            "temperature": 97.6,
            "heartrate": 70.0,
            "resprate": 16.0,
            "o2sat": 96.0,
            "sbp": 133.0,
            "dbp": 68.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "M",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "DYSPNEA",
            "age": 66.82124203,
            "tiragecase": "Male with end-stage COPD, CAD post-CABG, PE/DVT history, and amputation presented with acute worsening dyspnea and recurrent falls, disoriented on arrival.",
            "temperature": None,
            "heartrate": 60.0,
            "resprate": 12.0,
            "o2sat": 100.0,
            "sbp": None,
            "dbp": None,
        },
        "expected": {"final_esi_level": 1},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "AMBULANCE",
            "pain": "0",
            "chiefcomplaint": "Med refill",
            "age": 40.67049153,
            "tiragecase": "Female arrived by ambulance requesting medication refill with otherwise stable vitals and no pain.",
            "temperature": 99.6,
            "heartrate": 97.0,
            "resprate": 16.0,
            "o2sat": 97.0,
            "sbp": 120.0,
            "dbp": 70.0,
        },
        "expected": {"final_esi_level": 5},
    },
    {
        "input": {
            "gender": "M",
            "race": "ASIAN",
            "arrival_transport": "WALK IN",
            "pain": "5",
            "chiefcomplaint": "Neck pain, Headache",
            "age": 46.62818814,
            "tiragecase": "Male walk-in with neck pain and headache, stable vitals, and no neurologic or infectious red flags.",
            "temperature": 98.3,
            "heartrate": 77.0,
            "resprate": 16.0,
            "o2sat": 98.0,
            "sbp": 131.0,
            "dbp": 72.0,
        },
        "expected": {"final_esi_level": 3},
    },
    {
        "input": {
            "gender": "F",
            "race": "UNKNOWN",
            "arrival_transport": "UNKNOWN",
            "pain": "2",
            "chiefcomplaint": "L Leg injury, Transfer",
            "age": 40.39095845,
            "tiragecase": "Female transfer after fall with open tib-fib fracture, medial malleolar fracture, and metatarsal fracture, but stable vitals on arrival.",
            "temperature": 98.1,
            "heartrate": 100.0,
            "resprate": 16.0,
            "o2sat": 98.0,
            "sbp": 138.0,
            "dbp": 78.0,
        },
        "expected": {"final_esi_level": 2},
    },
    {
        "input": {
            "gender": "F",
            "race": "WHITE",
            "arrival_transport": "WALK IN",
            "pain": "6",
            "chiefcomplaint": "R Foot pain",
            "age": 24.51184679,
            "tiragecase": "Young female walk-in with isolated right foot pain, stable vitals, and no other symptoms.",
            "temperature": 98.9,
            "heartrate": 81.0,
            "resprate": 18.0,
            "o2sat": 99.0,
            "sbp": 148.0,
            "dbp": 86.0,
        },
        "expected": {"final_esi_level": 4},
    },
    {
        "input": {
            "gender": "M",
            "race": "BLACK/AFRICAN AMERICAN",
            "arrival_transport": "WALK IN",
            "pain": "9",
            "chiefcomplaint": "ABDOMINAL PAIN",
            "age": 37.95244606,
            "tiragecase": "Male with fistulizing Crohn's disease presented with severe anal pain, weight loss, purulent/bloody drainage, episodic fevers, and night sweats.",
            "temperature": 98.8,
            "heartrate": 77.0,
            "resprate": 18.0,
            "o2sat": 100.0,
            "sbp": 125.0,
            "dbp": 65.0,
        },
        "expected": {"final_esi_level": 2},
    },
]


def ensure_seed_esi_swarm_v1_mas_test_cases(db: Session) -> None:
    spec = get_workflow_spec(WORKFLOW_ID)
    evaluator = spec.test_evaluator
    if evaluator is None:
        return

    existing_names = set(
        db.execute(
            select(MasTestCase.name).where(MasTestCase.workflow_id == WORKFLOW_ID)
        ).scalars().all()
    )

    now = datetime.now(timezone.utc).replace(tzinfo=None)
    created_any = False

    for index, item in enumerate(SEEDED_ESI_SWARM_V1_CASES, start=1):
        chiefcomplaint = str(item["input"].get("chiefcomplaint") or "case").strip()
        name = f"Seed {index:02d} - {chiefcomplaint}"
        if name in existing_names:
            continue

        validated = spec.input_schema.model.model_validate(item["input"])
        normalized_input = validated.model_dump(mode="json")
        evaluator.validate_expected(item["expected"])

        db.add(
            MasTestCase(
                id=str(uuid.uuid4()),
                workflow_id=WORKFLOW_ID,
                name=name,
                enabled=True,
                input_json=normalized_input,
                expected_json=item["expected"],
                created_at=now,
                updated_at=now,
            )
        )
        created_any = True

    if created_any:
        db.commit()
